import { StoryAdventure, VocabularyWord } from "../types";
import gomaImage from "../assets/characters/goma.png";

const words: VocabularyWord[] = [
  { id: "observe", word: "관찰하다", meaning: "자세히 살펴보다.", example: "먼지 위의 발자국을 관찰했다.", simple: "자세히 보다", category: "thinking", difficulty: 1 },
  { id: "discover", word: "발견하다", meaning: "몰랐던 것을 찾아내다.", example: "책장 아래에서 작은 쪽지를 발견했다.", simple: "찾아내다", category: "thinking", difficulty: 1 },
  { id: "compare", word: "비교하다", meaning: "둘 이상의 같고 다른 점을 살펴보다.", example: "두 꽃가루의 색을 비교했다.", simple: "같고 다른 점 보기", category: "thinking", difficulty: 2 },
  { id: "confirm", word: "확인하다", meaning: "맞는지 다시 살펴보다.", example: "쪽지의 글씨를 확인했다.", simple: "다시 살피다", category: "thinking", difficulty: 1 },
  { id: "guess", word: "추측하다", meaning: "단서를 보고 미루어 생각하다.", example: "누가 왔는지 추측했다.", simple: "짐작하다", category: "thinking", difficulty: 2 },
  { id: "judge", word: "판단하다", meaning: "잘 생각해서 정하다.", example: "모두의 말을 듣고 판단했다.", simple: "생각해 정하다", category: "thinking", difficulty: 2 },
  { id: "explain", word: "설명하다", meaning: "남이 알기 쉽게 말해 주다.", example: "단서의 뜻을 설명했다.", simple: "알려 주다", category: "expression", difficulty: 1 },
  { id: "record", word: "기록하다", meaning: "잊지 않도록 적어 두다.", example: "오늘 찾은 단서를 공책에 기록했다.", simple: "적어 두다", category: "expression", difficulty: 1 },
  { id: "organize", word: "정리하다", meaning: "흩어진 것을 보기 좋게 모으다.", example: "단서를 순서대로 정리했다.", simple: "가지런히 하다", category: "expression", difficulty: 1 },
  { id: "classify", word: "분류하다", meaning: "기준에 따라 나누다.", example: "쪽지를 색깔별로 분류했다.", simple: "나누다", category: "expression", difficulty: 2 },
  { id: "discuss", word: "의논하다", meaning: "여럿이 생각을 나누다.", example: "친구들과 다음 길을 의논했다.", simple: "상담하다", category: "expression", difficulty: 1 },
  { id: "deliver", word: "전달하다", meaning: "말이나 물건을 다른 사람에게 전하다.", example: "선생님께 쪽지를 전달했다.", simple: "전해 주다", category: "expression", difficulty: 2 },
  { id: "faint", word: "희미하다", meaning: "분명하지 않고 흐릿하다.", example: "칠판에는 희미한 글자가 남아 있었다.", simple: "흐릿하다", category: "sense", difficulty: 1 },
  { id: "clear", word: "선명하다", meaning: "또렷하고 분명하다.", example: "햇빛이 닿자 글자가 선명해졌다.", simple: "또렷하다", category: "sense", difficulty: 1 },
  { id: "glimmer", word: "반짝이다", meaning: "작은 빛이 잠깐잠깐 빛나다.", example: "서랍 속 씨앗이 반짝였다.", simple: "빛나다", category: "sense", difficulty: 1 },
  { id: "rustle", word: "바스락대다", meaning: "마른 종이나 잎이 가볍게 스치는 소리가 나다.", example: "커튼 뒤에서 바스락대는 소리가 났다.", simple: "사각거리다", category: "sense", difficulty: 2 },
  { id: "quiet", word: "고요하다", meaning: "조용하고 잠잠하다.", example: "복도는 이상할 만큼 고요했다.", simple: "조용하다", category: "sense", difficulty: 1 },
  { id: "warm", word: "따스하다", meaning: "기분 좋게 따뜻하다.", example: "친구의 말이 마음을 따스하게 했다.", simple: "따뜻하다", category: "sense", difficulty: 1 },
  { id: "confused", word: "당황하다", meaning: "놀라서 어찌할 바를 모르다.", example: "하람은 사라진 글자를 보고 당황했다.", simple: "쩔쩔매다", category: "emotion", difficulty: 1 },
  { id: "relieved", word: "안심하다", meaning: "걱정이 없어져 마음이 놓이다.", example: "사실을 알게 된 민서는 안심했다.", simple: "마음 놓다", category: "emotion", difficulty: 1 },
  { id: "hurt", word: "서운하다", meaning: "마음에 모자라거나 섭섭하다.", example: "믿어 주지 않자 마음이 서운했다.", simple: "섭섭하다", category: "emotion", difficulty: 2 },
  { id: "unfair", word: "억울하다", meaning: "잘못한 일이 없는데 탓을 받아 속상하다.", example: "하람은 장난으로 몰려 억울했다.", simple: "속상하다", category: "emotion", difficulty: 2 },
  { id: "proud", word: "뿌듯하다", meaning: "해낸 일이 좋아 마음이 꽉 찬 듯하다.", example: "모두 함께 해결해서 뿌듯했다.", simple: "보람차다", category: "emotion", difficulty: 1 },
  { id: "hesitate", word: "망설이다", meaning: "바로 정하지 못하고 머뭇거리다.", example: "문 앞에서 잠시 망설였다.", simple: "머뭇거리다", category: "emotion", difficulty: 2 },
  { id: "appear", word: "나타나다", meaning: "보이지 않던 것이 보이게 되다.", example: "복도 끝에 새 문장이 나타났다.", simple: "보이다", category: "state", difficulty: 1 },
  { id: "vanish", word: "사라지다", meaning: "보이던 것이 없어지다.", example: "분필 글자가 먼지처럼 사라졌다.", simple: "없어지다", category: "state", difficulty: 1 },
  { id: "continue", word: "이어지다", meaning: "끊어지지 않고 계속 연결되다.", example: "발자국은 도서관까지 이어졌다.", simple: "계속되다", category: "state", difficulty: 1 },
  { id: "scatter", word: "흩어지다", meaning: "여기저기로 퍼지다.", example: "쪽지 조각이 바닥에 흩어졌다.", simple: "퍼지다", category: "state", difficulty: 1 },
  { id: "cause", word: "원인", meaning: "어떤 일이 생기게 된 까닭.", example: "글자가 사라진 원인을 찾았다.", simple: "까닭", category: "logic", difficulty: 2 },
  { id: "clue", word: "단서", meaning: "문제를 푸는 데 도움이 되는 작은 실마리.", example: "꽃가루는 중요한 단서였다.", simple: "실마리", category: "logic", difficulty: 2 },
  { id: "common", word: "공통점", meaning: "둘 이상에서 서로 같은 점.", example: "두 쪽지의 공통점은 같은 냄새였다.", simple: "같은 점", category: "logic", difficulty: 2 },
  { id: "standard", word: "기준", meaning: "나누거나 판단할 때 바탕이 되는 것.", example: "색깔을 기준으로 쪽지를 나누었다.", simple: "잣대", category: "logic", difficulty: 3 },
  { id: "conclusion", word: "결론", meaning: "생각이나 이야기를 마무리해 얻은 답.", example: "친구들은 함께 결론을 내렸다.", simple: "마지막 답", category: "logic", difficulty: 3 },
];

export const DEFAULT_ADVENTURE: StoryAdventure = {
  id: "whispering-board",
  title: "속삭이는 칠판",
  subtitle: "단어 씨앗을 되찾는 선택형 어휘 모험",
  mission: "이상한 문장을 읽고, 친구들과 단서를 모아 숲속 학교의 비밀을 밝히세요.",
  startSceneId: "morning-board",
  characters: [
    { id: "player", name: "주인공", role: "플레이어", color: "#FFFFFF", accent: "#111827" },
    { id: "rumi", name: "고마", role: "꼼꼼한 관찰자", color: "#E0F2FE", accent: "#0284C7", image: gomaImage },
    { id: "daram", name: "하람", role: "성급하지만 솔직한 친구", color: "#FEF3C7", accent: "#D97706" },
    { id: "bambi", name: "민서", role: "조심스러운 기록 담당", color: "#FCE7F3", accent: "#DB2777" },
    { id: "teacher", name: "서윤 선생님", role: "말의 길잡이", color: "#DCFCE7", accent: "#16A34A" },
    { id: "seed", name: "작은 목소리", role: "잊힌 단어 씨앗", color: "#EEF2FF", accent: "#4F46E5" },
  ],
  words,
  scenes: [
    {
      id: "morning-board",
      chapter: "1장",
      location: "3학년 교실",
      title: "지워지지 않는 아침",
      quizType: "meaning",
      focusWordId: "observe",
      focusText: "관찰했다",
      backgroundWordIds: ["faint", "glimmer", "confused"],
      lines: [
        { text: "아침 종이 울리기 전, 교실은 이상할 만큼 고요했다.", tone: "quiet" },
        { speakerId: "daram", text: "칠판에 누가 글씨를 썼어. 그런데 글자가... 움직이는 것 같아." },
        { text: "칠판 한가운데에는 희미한 문장이 남아 있었다. '작은 것을 그냥 지나치지 마.'", tone: "quiet" },
        { text: "창문 쪽 바닥에는 먼지가 얇게 쌓여 있었고, 그 위로 작은 점들이 이어져 있었다." },
        { speakerId: "player", text: "잠깐만. 그냥 지나치면 안 될 것 같아." },
        { text: "{player}는 먼지가 밀린 방향과 작은 발자국을 천천히 관찰했다." },
      ],
      prompt: "'관찰하다'의 뜻으로 알맞은 것은?",
      choices: [
        {
          id: "observe-correct",
          text: "자세히 살펴보다.",
          intent: "correct",
          wordId: "observe",
          feedback: "발자국의 방향과 작은 꽃가루를 알아냈다.",
          effect: { score: 3, nextSceneId: "under-shelf", flags: ["saw_footprints"], learnedWords: ["observe", "faint", "clue"], trust: { rumi: 1 } },
        },
        {
          id: "observe-wrong-alt",
          text: "소리 내어 말하다.",
          intent: "wrong",
          wordId: "confirm",
          feedback: "문장은 확인했지만, 창가의 단서는 놓쳤다.",
          effect: { score: 1, nextSceneId: "under-shelf", flags: ["read_board"], learnedWords: ["confirm"], reviewWords: ["observe"] },
        },
        {
          id: "observe-wrong",
          text: "깨끗이 지우다.",
          intent: "wrong",
          feedback: "지우개가 닿자 글자는 사라지고, 창가에서 바스락대는 소리만 남았다.",
          effect: { score: 0, nextSceneId: "under-shelf", flags: ["missed_first_clue"], reviewWords: ["observe", "faint"] },
        },
      ],
    },
    {
      id: "under-shelf",
      chapter: "1장",
      location: "책장 아래",
      title: "바스락대는 쪽지",
      quizType: "synonym",
      focusWordId: "discover",
      focusText: "발견했다",
      backgroundWordIds: ["rustle", "vanish"],
      reviewWordIds: ["observe"],
      lines: [
        { text: "책장 아래에서 마른 종이가 바스락대는 소리가 났다." },
        { speakerId: "bambi", text: "나... 무섭긴 한데, 저 종이 조각은 그냥 쓰레기 같지 않아." },
        { text: "쪽지는 책장 다리에 반쯤 가려져 있었다. 그냥 지나쳤다면 보지 못했을 만큼 작았다." },
        { speakerId: "player", text: "내가 조심히 꺼내 볼게." },
        { text: "{player}는 책장 틈에서 접힌 쪽지 한 장을 발견했다." },
      ],
      prompt: "'발견하다'와 뜻이 가까운 말은?",
      choices: [
        {
          id: "discover-correct",
          text: "찾아내다.",
          intent: "correct",
          wordId: "discover",
          feedback: "쪽지에서 달콤한 꽃향기와 작은 별 표시를 발견했다.",
          effect: { score: 3, nextSceneId: "pollen-compare", flags: ["found_note", "smelled_pollen"], learnedWords: ["discover", "confirm", "rustle"], trust: { bambi: 1 } },
        },
        {
          id: "discover-wrong-alt",
          text: "친구에게 전해 주다.",
          intent: "wrong",
          wordId: "deliver",
          feedback: "쪽지는 찾았지만, 자세한 흔적은 나중에 다시 살펴봐야 한다.",
          effect: { score: 1, nextSceneId: "pollen-compare", flags: ["found_note"], learnedWords: ["discover", "deliver"], reviewWords: ["confirm"] },
        },
        {
          id: "discover-wrong",
          text: "보이지 않게 숨기다.",
          intent: "wrong",
          feedback: "쪽지의 꽃가루가 주머니 안에서 흩어졌다.",
          effect: { score: 0, nextSceneId: "pollen-compare", flags: ["pollen_scattered"], reviewWords: ["discover", "scatter"] },
        },
      ],
    },
    {
      id: "pollen-compare",
      chapter: "2장",
      location: "창가와 화분대",
      title: "같은 노란색은 아니다",
      quizType: "usage",
      focusWordId: "compare",
      focusText: "비교했다",
      backgroundWordIds: ["common", "clear", "continue"],
      reviewWordIds: ["discover"],
      lines: [
        { speakerId: "rumi", text: "쪽지의 가루랑 화분의 가루를 비교해 보자. 둘 다 노란색이지만 완전히 같을까?" },
        { text: "햇빛이 들자 가루의 색이 더 선명해졌다. 하나는 레몬색, 하나는 금빛에 가까웠다." },
        { text: "고마는 손바닥 위에 흰 종이를 펴고, 두 가루가 섞이지 않게 조금씩 올려 두었다." },
        { speakerId: "player", text: "색만 보지 말고 냄새도 같이 살펴보자." },
        { text: "{player}는 쪽지의 가루와 화분의 가루를 나란히 놓고 비교했다." },
      ],
      prompt: "'비교하다'가 바르게 쓰인 문장은?",
      choices: [
        {
          id: "compare-correct",
          text: "두 가루의 색과 냄새를 비교했다.",
          intent: "correct",
          wordId: "compare",
          feedback: "두 가루의 차이를 찾아 도서관으로 이어지는 단서를 얻었다.",
          effect: { score: 3, nextSceneId: "quiet-hall", flags: ["compared_pollen"], learnedWords: ["compare", "common", "clear"], trust: { rumi: 1, daram: 1 } },
        },
        {
          id: "compare-wrong-alt",
          text: "쪽지를 친구에게 비교했다.",
          intent: "wrong",
          wordId: "common",
          feedback: "'비교하다'는 둘 사이의 같고 다른 점을 살필 때 쓰는 말이다.",
          effect: { score: 1, nextSceneId: "quiet-hall", flags: ["found_common"], learnedWords: ["common", "record"], reviewWords: ["compare"] },
        },
        {
          id: "compare-wrong",
          text: "복도를 조용히 비교했다.",
          intent: "wrong",
          wordId: "judge",
          feedback: "성급한 판단 때문에 고마가 고개를 저었다.",
          effect: { score: 0, nextSceneId: "quiet-hall", reviewWords: ["compare", "judge"], trust: { rumi: -1 } },
        },
      ],
    },
    {
      id: "quiet-hall",
      chapter: "2장",
      location: "도서관으로 가는 복도",
      title: "너무 조용한 복도",
      quizType: "blank",
      focusWordId: "guess",
      focusText: "추측했다",
      backgroundWordIds: ["quiet", "continue", "hesitate"],
      reviewWordIds: ["compare"],
      lines: [
        { text: "발자국은 복도 끝까지 이어졌다. 그런데 쉬는 시간인데도 복도에는 말소리가 없었다.", tone: "quiet" },
        { speakerId: "bambi", text: "발자국이 이어지는 걸 보니, 누가 도서관에 갔는지 추측할 수 있을 것 같아." },
        { text: "복도 창문은 닫혀 있었고, 꽃가루는 도서관 문 앞에서 더 많이 보였다." },
        { speakerId: "player", text: "그럼 도서관 안을 먼저 확인해 보자." },
        { text: "{player}는 발자국과 꽃가루를 보고 누군가 도서관에 갔다고 추측했다." },
      ],
      prompt: "발자국과 꽃가루를 보고 누군가 도서관에 갔다고 ____.",
      choices: [
        {
          id: "guess-correct",
          text: "추측했다.",
          intent: "correct",
          wordId: "guess",
          feedback: "친구들은 조심히 도서관 문을 열기로 했다.",
          effect: { score: 3, nextSceneId: "library-door", flags: ["guessed_library"], learnedWords: ["guess", "continue", "quiet"], trust: { bambi: 1 } },
        },
        {
          id: "guess-wrong-alt",
          text: "기록했다.",
          intent: "wrong",
          wordId: "record",
          feedback: "'기록했다'는 잊지 않게 적어 두었다는 뜻이다.",
          effect: { score: 1, nextSceneId: "library-door", learnedWords: ["record"], reviewWords: ["guess"] },
        },
        {
          id: "guess-wrong",
          text: "전달했다.",
          intent: "wrong",
          wordId: "deliver",
          feedback: "'전달했다'는 말이나 물건을 전해 주었다는 뜻이다.",
          effect: { score: 0, nextSceneId: "library-door", learnedWords: ["deliver"], reviewWords: ["guess"], trust: { daram: -1 } },
        },
      ],
    },
    {
      id: "library-door",
      chapter: "3장",
      location: "꿀빛 도서관",
      title: "흩어진 단어 카드",
      quizType: "situation",
      focusWordId: "classify",
      focusText: "분류했다",
      backgroundWordIds: ["scatter", "standard", "organize"],
      reviewWordIds: ["guess"],
      lines: [
        { text: "도서관 바닥에는 작은 카드들이 흩어져 있었다. 카드마다 낱말 하나와 짧은 문장이 적혀 있었다." },
        { speakerId: "teacher", text: "누군가 단어 씨앗을 깨웠구나. 흩어진 카드를 기준에 맞게 분류해야 길이 열릴 거야." },
        { text: "어떤 카드에는 움직임을 나타내는 말이, 어떤 카드에는 마음을 나타내는 말이 적혀 있었다." },
        { speakerId: "player", text: "그럼 비슷한 뜻끼리 모아 볼게요." },
        { text: "아이들은 카드를 행동, 마음, 느낌을 나타내는 말로 분류했다." },
      ],
      prompt: "'분류하다'를 쓸 수 있는 상황은?",
      choices: [
        {
          id: "classify-correct",
          text: "낱말 카드를 기준에 따라 나눌 때.",
          intent: "correct",
          wordId: "classify",
          feedback: "카드들이 제자리로 모이며 비밀 서가가 열렸다.",
          effect: { score: 3, nextSceneId: "misunderstanding", flags: ["classified_cards"], learnedWords: ["classify", "standard", "organize", "scatter"] },
        },
        {
          id: "classify-wrong-alt",
          text: "카드 한 장을 크게 읽을 때.",
          intent: "wrong",
          wordId: "organize",
          feedback: "보기에는 깔끔하지만, 단어의 뜻은 잘 드러나지 않았다.",
          effect: { score: 1, nextSceneId: "misunderstanding", learnedWords: ["organize"], reviewWords: ["classify", "standard"] },
        },
        {
          id: "classify-wrong",
          text: "마음에 드는 카드만 숨길 때.",
          intent: "wrong",
          feedback: "남은 카드들이 더 멀리 흩어졌다.",
          effect: { score: 0, nextSceneId: "misunderstanding", reviewWords: ["classify", "scatter"] },
        },
      ],
    },
    {
      id: "misunderstanding",
      chapter: "3장",
      location: "비밀 서가 앞",
      title: "장난이 아니었어",
      quizType: "synonym",
      focusWordId: "explain",
      focusText: "설명했다",
      backgroundWordIds: ["hurt", "unfair", "relieved"],
      reviewWordIds: ["classify"],
      lines: [
        { speakerId: "daram", text: "아까 나를 장난친 사람처럼 봤지? 나도 단서 찾으려고 한 건데." },
        { text: "하람의 목소리는 평소보다 작았다. {player}는 하람이 서운하고 억울했을지도 모른다고 생각했다." },
        { text: "{player}는 바로 변명하지 않았다. 먼저 하람의 표정을 보고, 친구들이 들은 단서를 떠올렸다." },
        { speakerId: "player", text: "내가 왜 그렇게 생각했는지 차근차근 말해 볼게." },
        { text: "{player}는 지금까지 찾은 단서와 생각한 이유를 차근차근 설명했다." },
      ],
      prompt: "'설명하다'와 뜻이 가까운 말은?",
      choices: [
        {
          id: "explain-correct",
          text: "알려 주다.",
          intent: "correct",
          wordId: "explain",
          feedback: "하람은 고개를 끄덕였고, 민서도 안심했다.",
          effect: { score: 3, nextSceneId: "notebook", flags: ["friends_reconciled"], learnedWords: ["explain", "hurt", "unfair", "relieved"], trust: { daram: 2, bambi: 1 } },
        },
        {
          id: "explain-wrong-alt",
          text: "혼자 조용히 생각하다.",
          intent: "wrong",
          feedback: "사과는 전했지만, 왜 그런 생각을 했는지는 남았다.",
          effect: { score: 1, nextSceneId: "notebook", learnedWords: ["hurt"], reviewWords: ["explain"] },
        },
        {
          id: "explain-wrong",
          text: "말하지 않고 지나가다.",
          intent: "wrong",
          feedback: "친구들의 발걸음이 조금 느려졌다.",
          effect: { score: 0, nextSceneId: "notebook", reviewWords: ["explain", "hurt", "relieved"], trust: { daram: -1, bambi: -1 } },
        },
      ],
    },
    {
      id: "notebook",
      chapter: "4장",
      location: "비밀 서가 안쪽",
      title: "잊지 않기 위한 공책",
      quizType: "blank",
      focusWordId: "record",
      focusText: "기록했다",
      backgroundWordIds: ["cause", "clue", "appear"],
      reviewWordIds: ["explain", "compare"],
      lines: [
        { text: "서가 안쪽에는 오래된 공책이 놓여 있었다. 첫 장에는 이렇게 적혀 있었다." },
        { speakerId: "seed", text: "말을 잊으면 마음도 흐려진다. 단서를 기록하는 아이만 마지막 문장을 읽을 수 있다.", tone: "quiet" },
        { text: "공책의 줄은 비어 있었지만, 손을 가까이 대자 연한 빛이 종이 위로 번졌다." },
        { speakerId: "player", text: "잊어버리지 않게 순서대로 적어 둘게." },
        { text: "{player}는 칠판 글씨, 발자국, 꽃가루, 카드를 순서대로 기록했다." },
      ],
      prompt: "잊지 않게 단서를 공책에 ____.",
      choices: [
        {
          id: "record-correct",
          text: "기록했다.",
          intent: "correct",
          wordId: "record",
          feedback: "공책의 빈 줄에 마지막 문장의 일부가 나타났다.",
          effect: { score: 3, nextSceneId: "cause-room", flags: ["kept_record"], learnedWords: ["record", "cause", "clue", "appear"] },
        },
        {
          id: "record-wrong-alt",
          text: "추측했다.",
          intent: "wrong",
          wordId: "guess",
          feedback: "'추측했다'는 단서를 보고 짐작했다는 뜻이다.",
          effect: { score: 1, nextSceneId: "cause-room", learnedWords: ["guess"], reviewWords: ["record"] },
        },
        {
          id: "record-wrong",
          text: "사라졌다.",
          intent: "wrong",
          feedback: "'사라졌다'는 보이던 것이 없어졌다는 뜻이다.",
          effect: { score: 0, nextSceneId: "cause-room", reviewWords: ["record", "faint"] },
        },
      ],
    },
    {
      id: "cause-room",
      chapter: "4장",
      location: "단어 씨앗 보관실",
      title: "왜 사라졌을까",
      quizType: "meaning",
      focusWordId: "cause",
      focusText: "원인",
      backgroundWordIds: ["vanish", "judge", "conclusion"],
      reviewWordIds: ["record"],
      lines: [
        { text: "보관실의 유리병은 비어 있었다. 병에는 '단어 씨앗'이라고 적힌 이름표만 남아 있었다." },
        { speakerId: "bambi", text: "씨앗이 사라진 원인을 찾아야 해. 누가 가져갔는지만 생각하면 놓치는 게 있을지도 몰라." },
        { text: "{player}는 공책에 적은 순서를 다시 보았다. 이상한 일들은 모두 낱말 카드가 흩어진 뒤에 시작되었다." },
        { speakerId: "player", text: "누가 가져갔는지보다 왜 사라졌는지 먼저 생각해 보자." },
        { speakerId: "teacher", text: "좋은 판단은 단서를 모두 보고 원인을 생각한 뒤에 하는 거란다." },
      ],
      prompt: "'원인'의 뜻으로 알맞은 것은?",
      choices: [
        {
          id: "cause-correct",
          text: "일이 생긴 까닭.",
          intent: "correct",
          wordId: "cause",
          feedback: "{player}는 씨앗이 누군가에게 끌려간 것이 아니라, 잊힌 단어를 따라 움직였다는 결론에 가까워졌다.",
          effect: { score: 3, nextSceneId: "last-voice", flags: ["understood_cause"], learnedWords: ["cause", "judge", "conclusion"] },
        },
        {
          id: "cause-wrong-alt",
          text: "마지막에 나온 답.",
          intent: "wrong",
          wordId: "judge",
          feedback: "가능성은 있지만, 아직 단서가 충분하지 않다.",
          effect: { score: 1, nextSceneId: "last-voice", learnedWords: ["judge"], reviewWords: ["cause"] },
        },
        {
          id: "cause-wrong",
          text: "서로 같은 점.",
          intent: "wrong",
          feedback: "작은 목소리가 유리병 안에서 다시 반짝였다.",
          effect: { score: 0, nextSceneId: "last-voice", reviewWords: ["cause", "conclusion"] },
        },
      ],
    },
    {
      id: "last-voice",
      chapter: "5장",
      location: "보관실의 둥근 창",
      title: "작은 목소리의 부탁",
      quizType: "usage",
      focusWordId: "deliver",
      focusText: "전달해야",
      backgroundWordIds: ["warm", "proud", "glimmer"],
      reviewWordIds: ["explain", "record", "cause"],
      lines: [
        { speakerId: "seed", text: "나는 도망친 게 아니야. 잊힌 낱말들이 나를 불렀어.", tone: "quiet" },
        { speakerId: "seed", text: "아이들이 '그냥 좋아', '그냥 싫어'라고만 말할 때마다 마음의 색이 흐려졌어." },
        { text: "{player}는 친구들의 얼굴을 떠올렸다. 정확한 말을 찾으면 마음도 더 분명해질 것 같았다." },
        { speakerId: "player", text: "그 말을 모두에게 전할게." },
        { text: "작은 씨앗은 따스한 빛으로 반짝였다. {player}는 마지막 문장을 친구들에게 전달해야 했다." },
      ],
      prompt: "'전달하다'가 바르게 쓰인 문장은?",
      choices: [
        {
          id: "deliver-correct",
          text: "나는 마지막 문장을 친구들에게 전달했다.",
          intent: "correct",
          wordId: "deliver",
          feedback: "친구들의 말이 또렷해지자 단어 씨앗이 다시 빛났다.",
          effect: { score: 3, nextSceneId: "ending-bright", flags: ["seed_restored"], learnedWords: ["deliver", "warm", "proud", "glimmer"], trust: { rumi: 1, daram: 1, bambi: 1 } },
        },
        {
          id: "deliver-wrong-alt",
          text: "나는 마지막 문장을 마음속에 전달했다.",
          intent: "wrong",
          wordId: "deliver",
          feedback: "씨앗은 돌아왔지만, 아직 되살려야 할 낱말이 남았다.",
          effect: { score: 1, nextSceneId: "ending-soft", flags: ["seed_found"], learnedWords: ["deliver"], reviewWords: ["explain", "record"] },
        },
        {
          id: "deliver-wrong",
          text: "나는 조용한 복도를 전달했다.",
          intent: "wrong",
          feedback: "씨앗은 작게 빛났지만, 몇 글자는 다시 희미해졌다.",
          effect: { score: 0, nextSceneId: "ending-soft", reviewWords: ["deliver", "explain", "proud"] },
        },
      ],
    },
    {
      id: "ending-bright",
      chapter: "끝",
      location: "3학년 교실",
      title: "말이 선명해진 날",
      lines: [
        { text: "다음 날 칠판에는 이상한 문장 대신, 친구들이 함께 만든 단어 지도가 붙어 있었다." },
        { speakerId: "daram", text: "나 이제 '그냥' 말고 제대로 말해 볼래. 어제는 억울했지만, 설명을 들으니 안심됐어." },
        { speakerId: "bambi", text: "기록해 두니까 정말 도움이 됐어. 우리 다음 사건도 해결할 수 있겠다." },
        { text: "{player}는 공책을 덮으며 뿌듯한 마음을 느꼈다. 말이 또렷해지자, 친구들의 마음도 조금 더 선명해졌다.", tone: "warm" },
      ],
      choices: [],
      ending: {
        title: "선명한 단어 씨앗 엔딩",
        message: "{player}와 친구들은 단어의 뜻뿐 아니라, 언제 어떻게 써야 하는지도 배웠다.",
      },
    },
    {
      id: "ending-soft",
      chapter: "끝",
      location: "조용한 교실",
      title: "다시 피울 씨앗",
      lines: [
        { text: "단어 씨앗은 돌아왔지만, 빛은 아직 작았다." },
        { speakerId: "teacher", text: "괜찮아. 낱말은 한 번에 모두 자라지 않아. 다시 읽고, 다시 써 보면 더 선명해진단다." },
        { speakerId: "rumi", text: "다음에는 우리가 놓친 단서까지 관찰해 보자." },
        { text: "{player}는 공책 첫 장에 오늘 다시 연습할 낱말을 적었다.", tone: "warm" },
      ],
      choices: [],
      ending: {
        title: "다시 자라는 단어 씨앗 엔딩",
        message: "아직 흐릿한 낱말이 남았다. 복습하면 더 좋은 결말에 닿을 수 있다.",
      },
    },
  ],
};

