import { StoryAdventure } from "../types";

export const DEFAULT_ADVENTURE: StoryAdventure = {
  id: "study-literary-words",
  title: "바람이 지나간 잎",
  subtitle: "학습도구어와 문학 어휘",
  mission: "이야기를 읽고 낱말을 익혀요.",
  startSceneId: "observe",
  words: [
    { id: "observe", word: "관찰하다", meaning: "자세히 살펴보다.", contextHint: "자세히 본다." },
    { id: "compare", word: "비교하다", meaning: "둘 이상의 같고 다른 점을 살펴보다.", contextHint: "같은 점과 다른 점을 본다." },
    { id: "infer", word: "추론하다", meaning: "단서를 보고 생각해 내다.", contextHint: "단서로 짐작한다." },
    { id: "classify", word: "분류하다", meaning: "기준에 따라 나누다.", contextHint: "무리로 나눈다." },
    { id: "record", word: "기록하다", meaning: "글이나 그림으로 남기다.", contextHint: "적어 둔다." },
    { id: "explain", word: "설명하다", meaning: "알기 쉽게 말해 주다.", contextHint: "이유를 말해 준다." },
    { id: "rustle", word: "살랑이다", meaning: "가볍고 부드럽게 움직이다.", contextHint: "바람에 조금씩 흔들린다." },
    { id: "faint", word: "희미하다", meaning: "또렷하지 않고 흐릿하다.", contextHint: "잘 보이지 않는다." },
    { id: "glimmer", word: "반짝이다", meaning: "작은 빛이 잠깐 빛나다.", contextHint: "빛이 난다." },
    { id: "cozy", word: "포근하다", meaning: "따뜻하고 편안하다.", contextHint: "마음이 편안하다." },
  ],
  scenes: [
    {
      id: "observe",
      chapter: "1장",
      location: "교실",
      focusWordId: "observe",
      questionType: "meaning",
      narrative: [
        "선생님은 여러 가지 잎을 책상 위에 놓았습니다.",
        "잎마다 색깔과 모양이 조금씩 달랐습니다.",
        "민지는 잎의 모양을 천천히 관찰했습니다.",
      ],
      prompt: "글 속 낱말 '관찰했습니다'의 뜻은?",
      choices: [
        { id: "observe-a", label: "A", text: "자세히 살펴보았습니다.", nextSceneId: "rustle", feedback: "좋아요.", points: 2, wordId: "observe" },
        { id: "observe-b", label: "B", text: "소리 내어 읽었습니다.", nextSceneId: "rustle", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "observe-c", label: "C", text: "빠르게 뛰었습니다.", nextSceneId: "rustle", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "observe-d", label: "D", text: "친구에게 나누어 주었습니다.", nextSceneId: "rustle", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "rustle",
      chapter: "2장",
      location: "창가",
      focusWordId: "rustle",
      questionType: "meaning",
      narrative: [
        "창문이 조금 열리자 바람이 들어왔습니다.",
        "얇은 잎 하나가 책상 위에서 살랑였습니다.",
        "아이들은 조용히 그 움직임을 바라보았습니다.",
      ],
      prompt: "글 속 낱말 '살랑였습니다'의 뜻은?",
      choices: [
        { id: "rustle-a", label: "A", text: "가볍게 움직였습니다.", nextSceneId: "compare", feedback: "맞아요.", points: 2, wordId: "rustle" },
        { id: "rustle-b", label: "B", text: "아주 세게 부딪혔습니다.", nextSceneId: "compare", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "rustle-c", label: "C", text: "완전히 멈추었습니다.", nextSceneId: "compare", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "rustle-d", label: "D", text: "큰 소리로 외쳤습니다.", nextSceneId: "compare", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "compare",
      chapter: "3장",
      location: "모둠 책상",
      focusWordId: "compare",
      questionType: "blank",
      narrative: [
        "둥근 잎과 길쭉한 잎을 나란히 놓았습니다.",
        "아이들은 두 잎의 같은 점과 다른 점을 찾았습니다.",
        "모둠은 두 잎을 비교했습니다.",
      ],
      prompt: "빈칸에 들어갈 낱말은?",
      choices: [
        { id: "compare-a", label: "A", text: "비교했습니다", nextSceneId: "faint", feedback: "맞아요.", points: 2, wordId: "compare" },
        { id: "compare-b", label: "B", text: "기록했습니다", nextSceneId: "faint", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "compare-c", label: "C", text: "설명했습니다", nextSceneId: "faint", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "compare-d", label: "D", text: "분류했습니다", nextSceneId: "faint", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "faint",
      chapter: "4장",
      location: "낡은 책",
      focusWordId: "faint",
      questionType: "synonym",
      narrative: [
        "책장 사이에서 오래된 잎 그림이 나왔습니다.",
        "그림 아래 글씨는 오래되어 희미했습니다.",
        "민지는 눈을 가까이 대고 글씨를 읽었습니다.",
      ],
      prompt: "'희미했습니다'와 비슷한 뜻은?",
      choices: [
        { id: "faint-a", label: "A", text: "흐릿했습니다.", nextSceneId: "infer", feedback: "좋아요.", points: 2, wordId: "faint" },
        { id: "faint-b", label: "B", text: "시끄러웠습니다.", nextSceneId: "infer", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "faint-c", label: "C", text: "무거웠습니다.", nextSceneId: "infer", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "faint-d", label: "D", text: "차가웠습니다.", nextSceneId: "infer", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "infer",
      chapter: "5장",
      location: "창가",
      focusWordId: "infer",
      questionType: "definitionToWord",
      narrative: [
        "창가의 잎은 다른 잎보다 더 진한 초록색이었습니다.",
        "창가에는 햇빛이 오래 들어왔습니다.",
        "민지는 햇빛 때문에 잎 색이 진해졌다고 추론했습니다.",
      ],
      prompt: "이 장면에 알맞은 낱말은?",
      choices: [
        { id: "infer-a", label: "A", text: "추론했습니다", nextSceneId: "classify", feedback: "좋아요.", points: 2, wordId: "infer" },
        { id: "infer-b", label: "B", text: "관찰했습니다", nextSceneId: "classify", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "infer-c", label: "C", text: "기록했습니다", nextSceneId: "classify", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "infer-d", label: "D", text: "비교했습니다", nextSceneId: "classify", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "classify",
      chapter: "6장",
      location: "칠판 앞",
      focusWordId: "classify",
      questionType: "situation",
      narrative: [
        "아이들은 잎을 모양에 따라 나누었습니다.",
        "둥근 잎은 왼쪽, 길쭉한 잎은 오른쪽에 붙였습니다.",
        "선생님은 기준을 정해 나누었다고 말했습니다.",
      ],
      prompt: "이 상황에 어울리는 낱말은?",
      choices: [
        { id: "classify-a", label: "A", text: "분류했습니다", nextSceneId: "glimmer", feedback: "맞아요.", points: 2, wordId: "classify" },
        { id: "classify-b", label: "B", text: "설명했습니다", nextSceneId: "glimmer", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "classify-c", label: "C", text: "관찰했습니다", nextSceneId: "glimmer", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "classify-d", label: "D", text: "추론했습니다", nextSceneId: "glimmer", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "glimmer",
      chapter: "7장",
      location: "복도",
      focusWordId: "glimmer",
      questionType: "blank",
      narrative: [
        "복도 창으로 오후 햇살이 들어왔습니다.",
        "잎 표면의 작은 물방울이 반짝였습니다.",
        "아이들은 빛나는 잎을 보며 감탄했습니다.",
      ],
      prompt: "빈칸에 들어갈 낱말은?",
      choices: [
        { id: "glimmer-a", label: "A", text: "반짝였습니다", nextSceneId: "record", feedback: "맞아요.", points: 2, wordId: "glimmer" },
        { id: "glimmer-b", label: "B", text: "희미했습니다", nextSceneId: "record", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "glimmer-c", label: "C", text: "분류했습니다", nextSceneId: "record", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "glimmer-d", label: "D", text: "설명했습니다", nextSceneId: "record", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "record",
      chapter: "8장",
      location: "탐구 노트",
      focusWordId: "record",
      questionType: "synonym",
      narrative: [
        "민지는 잎의 모양과 색깔을 노트에 적었습니다.",
        "친구들은 알게 된 내용을 그림으로도 남겼습니다.",
        "모둠은 결과를 탐구 노트에 기록했습니다.",
      ],
      prompt: "'기록했습니다'와 비슷한 뜻은?",
      choices: [
        { id: "record-a", label: "A", text: "적어 두었습니다.", nextSceneId: "cozy", feedback: "좋아요.", points: 2, wordId: "record" },
        { id: "record-b", label: "B", text: "무리로 나누었습니다.", nextSceneId: "cozy", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "record-c", label: "C", text: "단서를 보고 생각했습니다.", nextSceneId: "cozy", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "record-d", label: "D", text: "알기 쉽게 말했습니다.", nextSceneId: "cozy", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "cozy",
      chapter: "9장",
      location: "도서관",
      focusWordId: "cozy",
      questionType: "meaning",
      narrative: [
        "아이들은 도서관 창가에 둘러앉았습니다.",
        "햇살이 따뜻하게 내려와 자리가 포근했습니다.",
        "민지는 그곳에서 발표할 말을 조용히 떠올렸습니다.",
      ],
      prompt: "글 속 낱말 '포근했습니다'의 뜻은?",
      choices: [
        { id: "cozy-a", label: "A", text: "따뜻하고 편안했습니다.", nextSceneId: "explain", feedback: "좋아요.", points: 2, wordId: "cozy" },
        { id: "cozy-b", label: "B", text: "무섭고 어두웠습니다.", nextSceneId: "explain", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "cozy-c", label: "C", text: "매우 시끄러웠습니다.", nextSceneId: "explain", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "cozy-d", label: "D", text: "차갑고 딱딱했습니다.", nextSceneId: "explain", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "explain",
      chapter: "10장",
      location: "발표 자리",
      focusWordId: "explain",
      questionType: "blank",
      narrative: [
        "발표 시간이 되자 민지가 앞으로 나왔습니다.",
        "민지는 잎을 나눈 기준과 이유를 친구들에게 말했습니다.",
        "민지는 탐구 결과를 설명했습니다.",
      ],
      prompt: "빈칸에 들어갈 낱말은?",
      choices: [
        { id: "explain-a", label: "A", text: "설명했습니다", nextSceneId: "complete", feedback: "맞아요.", points: 2, wordId: "explain" },
        { id: "explain-b", label: "B", text: "관찰했습니다", nextSceneId: "complete", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "explain-c", label: "C", text: "비교했습니다", nextSceneId: "complete", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "explain-d", label: "D", text: "기록했습니다", nextSceneId: "complete", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "complete",
      chapter: "완료",
      location: "교실",
      narrative: ["탐구 노트와 낱말 이야기가 완성되었습니다."],
      prompt: "끝",
      choices: [],
      ending: {
        title: "완성!",
        message: "끝",
      },
    },
  ],
};
