import { StoryAdventure } from "../types";

export const DEFAULT_ADVENTURE: StoryAdventure = {
  id: "goma-story-words",
  title: "고마 이야기",
  subtitle: "학습도구어와 문학 어휘",
  mission: "고마와 함께 이야기를 읽고 낱말을 익혀요.",
  startSceneId: "observe",
  words: [
    { id: "observe", word: "관찰하다", meaning: "자세히 살펴보다.", contextHint: "자세히 본다." },
    { id: "compare", word: "비교하다", meaning: "둘 이상의 같고 다른 점을 살펴보다.", contextHint: "같은 점과 다른 점을 본다." },
    { id: "infer", word: "추론하다", meaning: "단서를 보고 생각해 내다.", contextHint: "단서로 짐작한다." },
    { id: "classify", word: "분류하다", meaning: "기준에 따라 나누다.", contextHint: "무리로 나눈다." },
    { id: "record", word: "기록하다", meaning: "글이나 그림으로 남기다.", contextHint: "적어 둔다." },
    { id: "explain", word: "설명하다", meaning: "알기 쉽게 말해 주다.", contextHint: "이유를 말해 준다." },
    { id: "rustle", word: "살랑이다", meaning: "가볍고 부드럽게 움직이다.", contextHint: "바람에 조금씩 흔들린다." },
    { id: "faint", word: "희미하다", meaning: "또렷하지 않고 흐릿하다.", contextHint: "잘 보이지 않는다." },
    { id: "glimmer", word: "반짝이다", meaning: "작은 빛이 잠깐 빛나다.", contextHint: "빛이 난다." },
    { id: "cozy", word: "포근하다", meaning: "따뜻하고 편안하다.", contextHint: "마음이 편안하다." },
  ],
  scenes: [
    {
      id: "observe",
      chapter: "1장",
      location: "숲속 교실",
      focusWordId: "observe",
      questionType: "meaning",
      narrative: [
        "곰 친구 고마는 숲속 학교 3학년입니다.",
        "어느 아침, 교실 창가에 작은 꿀단지가 놓여 있었습니다.",
        "고마는 꿀단지 옆의 발자국과 꽃가루를 천천히 관찰했습니다.",
      ],
      prompt: "글 속 낱말 '관찰했습니다'의 뜻은?",
      choices: [
        { id: "observe-a", label: "A", text: "자세히 살펴보았습니다.", nextSceneId: "rustle", feedback: "좋아요.", points: 2, wordId: "observe" },
        { id: "observe-b", label: "B", text: "큰 소리로 노래했습니다.", nextSceneId: "rustle", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "observe-c", label: "C", text: "빨리 달려갔습니다.", nextSceneId: "rustle", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "observe-d", label: "D", text: "친구에게 숨겼습니다.", nextSceneId: "rustle", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "rustle",
      chapter: "2장",
      location: "교실 창가",
      focusWordId: "rustle",
      questionType: "meaning",
      narrative: [
        "고마가 창문을 열자 봄바람이 살짝 들어왔습니다.",
        "창가에 꽂아 둔 풀잎이 바람에 살랑였습니다.",
        "고마는 풀잎이 가리키는 쪽에 작은 종이쪽지가 있다는 것을 보았습니다.",
      ],
      prompt: "글 속 낱말 '살랑였습니다'의 뜻은?",
      choices: [
        { id: "rustle-a", label: "A", text: "가볍게 움직였습니다.", nextSceneId: "compare", feedback: "맞아요.", points: 2, wordId: "rustle" },
        { id: "rustle-b", label: "B", text: "아주 세게 부딪혔습니다.", nextSceneId: "compare", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "rustle-c", label: "C", text: "완전히 사라졌습니다.", nextSceneId: "compare", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "rustle-d", label: "D", text: "큰 소리로 울었습니다.", nextSceneId: "compare", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "compare",
      chapter: "3장",
      location: "모둠 책상",
      focusWordId: "compare",
      questionType: "blank",
      narrative: [
        "쪽지에는 노란 꽃가루가 묻어 있었습니다.",
        "고마는 꿀단지 옆 꽃가루와 쪽지의 꽃가루를 나란히 놓았습니다.",
        "고마와 친구들은 색과 모양을 비교했습니다.",
      ],
      prompt: "빈칸에 들어갈 낱말은?",
      choices: [
        { id: "compare-a", label: "A", text: "비교했습니다", nextSceneId: "faint", feedback: "맞아요.", points: 2, wordId: "compare" },
        { id: "compare-b", label: "B", text: "기록했습니다", nextSceneId: "faint", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "compare-c", label: "C", text: "설명했습니다", nextSceneId: "faint", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "compare-d", label: "D", text: "분류했습니다", nextSceneId: "faint", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "faint",
      chapter: "4장",
      location: "낡은 지도",
      focusWordId: "faint",
      questionType: "synonym",
      narrative: [
        "쪽지 뒤에는 아주 오래된 숲 지도가 그려져 있었습니다.",
        "비에 젖었던 흔적 때문에 길 이름이 희미했습니다.",
        "고마는 눈을 가늘게 뜨고 흐릿한 글자를 읽어 보았습니다.",
      ],
      prompt: "'희미했습니다'와 비슷한 뜻은?",
      choices: [
        { id: "faint-a", label: "A", text: "흐릿했습니다.", nextSceneId: "infer", feedback: "좋아요.", points: 2, wordId: "faint" },
        { id: "faint-b", label: "B", text: "시끄러웠습니다.", nextSceneId: "infer", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "faint-c", label: "C", text: "무거웠습니다.", nextSceneId: "infer", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "faint-d", label: "D", text: "차가웠습니다.", nextSceneId: "infer", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "infer",
      chapter: "5장",
      location: "민들레 길",
      focusWordId: "infer",
      questionType: "definitionToWord",
      narrative: [
        "지도에는 민들레 그림과 꿀벌 발자국이 함께 남아 있었습니다.",
        "교실 쪽지에도 같은 노란 꽃가루가 묻어 있었습니다.",
        "고마는 누군가 민들레 길에서 왔다고 추론했습니다.",
      ],
      prompt: "이 장면에 알맞은 낱말은?",
      choices: [
        { id: "infer-a", label: "A", text: "추론했습니다", nextSceneId: "classify", feedback: "좋아요.", points: 2, wordId: "infer" },
        { id: "infer-b", label: "B", text: "관찰했습니다", nextSceneId: "classify", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "infer-c", label: "C", text: "기록했습니다", nextSceneId: "classify", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "infer-d", label: "D", text: "비교했습니다", nextSceneId: "classify", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "classify",
      chapter: "6장",
      location: "숲길 입구",
      focusWordId: "classify",
      questionType: "situation",
      narrative: [
        "고마와 친구들은 길에서 찾은 단서를 책상 위에 펼쳤습니다.",
        "발자국은 모양별로, 꽃가루는 색깔별로, 쪽지는 장소별로 나누었습니다.",
        "친구들은 기준을 세워 단서를 분류했습니다.",
      ],
      prompt: "이 상황에 어울리는 낱말은?",
      choices: [
        { id: "classify-a", label: "A", text: "분류했습니다", nextSceneId: "glimmer", feedback: "맞아요.", points: 2, wordId: "classify" },
        { id: "classify-b", label: "B", text: "설명했습니다", nextSceneId: "glimmer", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "classify-c", label: "C", text: "관찰했습니다", nextSceneId: "glimmer", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "classify-d", label: "D", text: "추론했습니다", nextSceneId: "glimmer", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "glimmer",
      chapter: "7장",
      location: "시냇가",
      focusWordId: "glimmer",
      questionType: "blank",
      narrative: [
        "민들레 길 끝에는 맑은 시냇물이 흐르고 있었습니다.",
        "물가의 돌 위에서 작은 꿀방울 하나가 햇빛을 받아 반짝였습니다.",
        "고마는 빛나는 꿀방울을 보고 길을 더 따라가 보기로 했습니다.",
      ],
      prompt: "빈칸에 들어갈 낱말은?",
      choices: [
        { id: "glimmer-a", label: "A", text: "반짝였습니다", nextSceneId: "record", feedback: "맞아요.", points: 2, wordId: "glimmer" },
        { id: "glimmer-b", label: "B", text: "희미했습니다", nextSceneId: "record", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "glimmer-c", label: "C", text: "분류했습니다", nextSceneId: "record", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "glimmer-d", label: "D", text: "설명했습니다", nextSceneId: "record", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "record",
      chapter: "8장",
      location: "고마의 탐정 노트",
      focusWordId: "record",
      questionType: "synonym",
      narrative: [
        "고마는 지금까지 찾은 단서를 탐정 노트에 적었습니다.",
        "발자국 그림, 꽃가루 색, 꿀방울 위치도 빠뜨리지 않았습니다.",
        "고마는 알게 된 내용을 차례대로 기록했습니다.",
      ],
      prompt: "'기록했습니다'와 비슷한 뜻은?",
      choices: [
        { id: "record-a", label: "A", text: "적어 두었습니다.", nextSceneId: "cozy", feedback: "좋아요.", points: 2, wordId: "record" },
        { id: "record-b", label: "B", text: "무리로 나누었습니다.", nextSceneId: "cozy", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "record-c", label: "C", text: "단서를 보고 생각했습니다.", nextSceneId: "cozy", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "record-d", label: "D", text: "알기 쉽게 말했습니다.", nextSceneId: "cozy", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "cozy",
      chapter: "9장",
      location: "꿀벌 할머니의 집",
      focusWordId: "cozy",
      questionType: "meaning",
      narrative: [
        "단서를 따라가자 작은 나무집이 보였습니다.",
        "집 안에는 따뜻한 차 냄새와 달콤한 꿀 향기가 가득해 포근했습니다.",
        "꿀벌 할머니는 고마를 보고 미안한 표정으로 웃었습니다.",
      ],
      prompt: "글 속 낱말 '포근했습니다'의 뜻은?",
      choices: [
        { id: "cozy-a", label: "A", text: "따뜻하고 편안했습니다.", nextSceneId: "explain", feedback: "좋아요.", points: 2, wordId: "cozy" },
        { id: "cozy-b", label: "B", text: "무섭고 어두웠습니다.", nextSceneId: "explain", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "cozy-c", label: "C", text: "매우 시끄러웠습니다.", nextSceneId: "explain", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "cozy-d", label: "D", text: "차갑고 딱딱했습니다.", nextSceneId: "explain", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "explain",
      chapter: "10장",
      location: "숲속 교실",
      focusWordId: "explain",
      questionType: "blank",
      narrative: [
        "꿀벌 할머니는 교실에 선물하려고 꿀단지를 가져다 놓았다고 했습니다.",
        "하지만 바람에 쪽지가 날아가서 모두가 궁금해했던 것입니다.",
        "고마는 단서를 찾은 방법과 꿀단지의 사연을 친구들에게 설명했습니다.",
      ],
      prompt: "빈칸에 들어갈 낱말은?",
      choices: [
        { id: "explain-a", label: "A", text: "설명했습니다", nextSceneId: "complete", feedback: "맞아요.", points: 2, wordId: "explain" },
        { id: "explain-b", label: "B", text: "관찰했습니다", nextSceneId: "complete", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "explain-c", label: "C", text: "비교했습니다", nextSceneId: "complete", feedback: "다시 생각해 봐요.", points: 0 },
        { id: "explain-d", label: "D", text: "기록했습니다", nextSceneId: "complete", feedback: "다시 생각해 봐요.", points: 0 },
      ],
    },
    {
      id: "complete",
      chapter: "완료",
      location: "숲속 교실",
      narrative: ["고마와 친구들은 꿀차를 나누어 마시며 오늘 배운 낱말을 다시 떠올렸습니다."],
      prompt: "끝",
      choices: [],
      ending: {
        title: "고마의 낱말 모험 완성!",
        message: "끝",
      },
    },
  ],
};
